export const wordsList = [
  "Do chuja wafla", 
  "Wyparcie", 
  "Interwencja GM`a", 
  "Szlachetka", 
  "Ubliżanie rycerzowi/szlachcicowi", 
  "Daku ratuje dzień", 
  "Bohater imperium z tyłu", 
  "Kolegium ognia", 
  "Alkoholizm", 
  "Ignorowanie zasad świata", 
  "Używanie slangu współczesnego", 
  "Zapominanie imienia", 
  "Nie pamiętam", 
  "Mogę rzucić na inteligencję?", 
  "To ja rzucam żądełko", 
  "Ale ja się na to nie pisałem", 
  "Modlę się do Vereny", 
  "Ciemne wszędzie głucho wszędzie co to będzie, co to będzie...", 
  "Chyba cię dupa szczypie", 
  "Słowo szlachcica/rycerza", 
  "Ty łajdaku!", 
  "Szlachcic z Parravonu", 
  "To ja idę kuć", 
  "Modlę się do Przodków", 
  "Nie używaj magii", 
  "Uśmiecham się filuternie", 
  "Tskimaru", 
  "Mogę przerzucić?", 
  "Korona Bretonni dowie się o tym", 
  "Ja się na to nie pisałem",
  "Ekchart sam sie pogrąża",
  "Ja nie będę pił tych szczyn",
  "Obrażanie bogów",
  "Ja panu nie przerywałem",
];
